# Generated by Django 3.1 on 2021-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210601_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='espaco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='processada',
        ),
    ]
