# Generated by Django 3.1 on 2021-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='espaco',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
