# Generated by Django 3.1 on 2021-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210601_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='espaco',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
