# Generated by Django 3.1 on 2021-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210601_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='processada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
