# Generated by Django 3.1 on 2021-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210611_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='espaco',
        ),
        migrations.AddField(
            model_name='user',
            name='espaco1',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
