# Generated by Django 3.1 on 2021-07-29 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemOrg', models.ImageField(default='default.jpg', upload_to='')),
                ('imagemPro', models.ImageField(default='default.jpg', upload_to='')),
                ('tumb', models.ImageField(default='default.jpg', upload_to='')),
                ('porcentagemPro', models.IntegerField(default=0)),
                ('quantPlantas', models.IntegerField(default=0)),
                ('tamanho', models.FloatField(default=0)),
                ('altura', models.IntegerField(default=0)),
                ('largura', models.IntegerField(default=0)),
                ('processada', models.CharField(default='0', max_length=1)),
                ('fila', models.BooleanField(default=False)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imagem',
            },
        ),
    ]
