# Generated by Django 3.1 on 2021-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemOrg', models.ImageField(upload_to='')),
                ('imagemPro', models.ImageField(upload_to='')),
                ('processada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'imagem',
            },
        ),
    ]
