# Generated by Django 3.1 on 2021-06-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagem',
            table='Imagem',
        ),
    ]
