# Generated by Django 3.1 on 2021-07-29 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='temp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
