# Generated by Django 3.1 on 2021-06-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0002_auto_20210601_1154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagem',
            table='imagem',
        ),
    ]
