# Generated by Django 3.1 on 2021-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0002_imagem_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='area',
            field=models.FloatField(default=-1),
        ),
    ]
