# Generated by Django 3.1 on 2021-08-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0003_imagem_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='tumbPro',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
