# Generated by Django 3.1 on 2021-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0004_auto_20210601_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='processada',
            field=models.BooleanField(default=False),
        ),
    ]
