# Generated by Django 3.1 on 2021-06-01 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milho', '0007_auto_20210601_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
