# Generated by Django 3.1 on 2021-06-07 16:03

from django.db import migrations, models
import milho.validators


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0008_auto_20210601_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='filepath',
            field=models.FileField(default='', upload_to='media/', validators=[milho.validators.validate_file_size], verbose_name=''),
        ),
    ]
