# Generated by Django 3.1 on 2021-06-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0009_imagem_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='filepath',
        ),
    ]
