# Generated by Django 3.1 on 2021-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0010_remove_imagem_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='processada',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
