# Generated by Django 3.1 on 2021-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0011_auto_20210611_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagemOrg',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagemPro',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
