# Generated by Django 3.1 on 2021-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milho', '0013_auto_20210611_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='quantPlantas',
            field=models.IntegerField(default=0),
        ),
    ]
